{% set name = "pnpm" %}
{% set version = "10.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 80d408c605123eabc9d5fdcd2d796bcbc43109623aaa523a02e46a141a0f319a

build:
  number: 0
  ignore_run_exports:
    - nodejs
    - vs2015_runtime
  # nodejs is not avaliable on linux-s390x
  skip: True  # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [not win]
    # https://pnpm.io/installation#compatibility
    # pnpm 10.4.1 requires nodejs 20+ due to dependencies
    - nodejs >=20
  host:
    - nodejs >=20
  run:
    - nodejs >=20
    - vs2015_runtime  # [win]

test:
  commands:
    - pnpm --help

about:
  home: https://pnpm.io/
  summary: 📦🚀 Fast, disk space efficient package manager
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  description: Fast, disk space efficient package manager
  dev_url: https://github.com/pnpm/pnpm
  doc_url: https://pnpm.io/motivation

extra:
  recipe-maintainers:
    - JaninaWibkerQC
    - xhochy
    - pavelzw
  skip-lints:
    - host_section_needs_exact_pinnings
